enum SettingsKeys {
    static let hasLaunchedBefore = "hasLaunchedBefore"
    static let enabled = "enabled"
    static let ollamaURL = "ollamaURL"
    static let model = "model"
    static let debounceMs = "debounceMs"
    static let completionLength = "completionLength"
    static let contextChars = "contextChars"
    static let clipboardAwareness = "clipboardAwareness"
    static let screenAwareMode = "screenAwareMode"
    static let personalizationLevel = "personalizationLevel"
    static let customInstructions = "customInstructions"
    static let perAppInstructions = "perAppInstructions"
    static let enableEmoji = "enableEmoji"
    static let enableTypoDetection = "enableTypoDetection"
    static let enableMidLine = "enableMidLine"
    static let debugMode = "debugMode"
    static let blockedBundleIDs = "blockedBundleIDs"
    static let enableMacros = "enableMacros"
    static let overlayOpacity = "overlayOpacity"
    static let statsAcceptedAllTime = "statsAcceptedAllTime"
    static let statsWordsSavedAllTime = "statsWordsSavedAllTime"
    static let statsLatencySamples = "statsLatencySamples"
    static let statsDailyPrefix = "statsDaily_"
}
